# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: droxops/mosaic-node-py:0.0.4

    working_directory: ~/repo

    steps:
      # checkout the code of the branch from github, which triggers the build
      - checkout

      - restore_cache:
          keys:
            - node-dependency-cache-{{ checksum "package.json" }}
            - node-dependency-cache-

      - run:
          name: install node dependencies
          working_directory: impress_plugin
          command: npm install

      - save_cache:
          key: node-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      ### run automatic tests
      - run:
          working_directory: impress_plugin
          name: run node tests
          command: |
            . ../venv/bin/activate
            npm test


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build


