# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test_build_deploy:
    docker:
      - image: droxops/mosaic-node-py:0.0.4

    working_directory: ~/repo

    steps:
      # checkout the code of the branch from github, which triggers the build
      - checkout

      - restore_cache:
          keys:
            - node-dependency-cache-{{ checksum "package.json" }}
            - node-dependency-cache-

      - run:
          name: install node dependencies
          command: npm install

      - save_cache:
          key: node-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      ### run automatic tests
      - run:
          name: run node tests
          command: npm test

      - add_ssh_keys:
          fingerprints:
            - "10:56:b2:4e:00:a7:3d:a4:82:f2:48:7c:38:86:18:2c"

      - run:
          name: build node package
          command: |
            export impress_folder='~/repo/roxconnector/release'
            if [ $CIRCLE_BRANCH != 'master' ]; then sed -i -e "s/\"version\".*/\"version\":\"$(cat VERSION)-dev$CIRCLE_BUILD_NUM\",/" package.json; export impress_folder='~/repo/roxconnector/dev'; fi
            scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./$(npm pack) artifact@artifacts.droxit.de:$impress_folder


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test_build_deploy


